### ISSUE TITLE
it makes the game boring

### ISSUE THREAD

**Issue by twnlink** [Snektective/snek-extension#3]
plz fix

**Comment by relative2** [comment]
can confirm

**Comment by 7coil** [comment]
🤔

**Comment by relative2** [comment]
this is gonna have to be a fat reopen

**Comment by 7coil** [comment]
[![haha](https://user-images.githubusercontent.com/13886925/55439543-da76f900-559c-11e9-929f-c1e11a72e75f.png)](https://twitter.com/loonatheworld)
no
no reopen

**Comment by twnlink** [comment]
yes yes reopen

**Comment by haykam821** [comment]
🐍
