### ISSUE TITLE
the game fucking sucks

### ISSUE THREAD

**Issue by aspencuozzo** [Snektective/snek-extension#6]
please fix the entire game or just cancel it thanks

spez edit: fixed

**Comment by twnlink** [comment]
+1, can reproduce

**Comment by Aria-NL** [comment]
he's right

**Comment by relative2** [comment]
+1, can reproduce

**Comment by Mrzoo123** [comment]
+1. reproduced first time

**Comment by DashLt** [comment]
oh hey the one aspect in which I do have power

**Comment by DashLt** [comment]
@haykam821 so, how's the weather today

**Comment by haykam821** [comment]
It’s not raining nukes outside today, which is always a good sign.

**Comment by DashLt** [comment]
yes indeed we need to fix cosmo

**Comment by relative2** [comment]
we need to fix @DashLt

**Comment by aspencuozzo** [comment]
i need to fix u you fuckin WEEB

**Comment by DashLt** [comment]
your profile picture was CC from code geass for how many months

**Comment by meyerdg** [comment]
wat

**Comment by aspencuozzo** [comment]
like one month you jizz ur pants over yuri shut up

**Comment by Aria-NL** [comment]
go off @cosmopath

**Comment by 9hp** [comment]
# april fools
funny, got you good!

**Comment by DashLt** [comment]
> like one month you jizz ur pants over yuri shut up

your idea of humor is a dancing lizard posted about 10 times a day

**Comment by aspencuozzo** [comment]
>your idea of humor is a dancing lizard posted about 10 times a day

because that IS what humour is 
hah, im spez i can edit comments

**Comment by twnlink** [comment]
I've submitted a pr as a fix, please check it out at #7

**Comment by relative2** [comment]
excuse me remove that fucking wontfix label you little shit

**Comment by FNCxPro** [comment]
..- / ..--.

**Comment by DashLt** [comment]
remove the swarm and we'll be fine

**Comment by aspencuozzo** [comment]
>remove the swarm and we'll be fine

remove yourself from this planet

**Comment by DashLt** [comment]
no u

**Comment by 9hp** [comment]
> excuse me remove that fucking wontfix label you little shit

wont fix

**Comment by 9hp** [comment]
> > excuse me remove that fucking wontfix label you little shit
> 
> wont fix

wont fix

**Comment by 9hp** [comment]
> > > excuse me remove that fucking wontfix label you little shit
> > 
> > 
> > wont fix
> 
> wont fix

wont fix

**Comment by 9hp** [comment]
> > > > excuse me remove that fucking wontfix label you little shit
> > > 
> > > 
> > > wont fix
> > 
> > 
> > wont fix
> 
> wont fix

farming commits

**Comment by 9hp** [comment]
> > > > > excuse me remove that fucking wontfix label you little shit
> > > > 
> > > > 
> > > > wont fix
> > > 
> > > 
> > > wont fix
> > 
> > 
> > wont fix
> 
> farming commits

twitter for android

**Comment by DashLt** [comment]
> > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > 
> > > > > 
> > > > > wont fix
> > > > 
> > > > 
> > > > wont fix
> > > 
> > > 
> > > wont fix
> > 
> > 
> > farming commits
> 
> twitter for android

day after day

**Comment by FNCxPro** [comment]
> 
> 
> > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > 
> > > > > 
> > > > > wont fix
> > > > 
> > > > 
> > > > wont fix
> > > 
> > > 
> > > wont fix
> > 
> > 
> > farming commits
> 
> twitter for android

no one cares you little shit

**Comment by relative2** [comment]
> 
> 
> > > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > > 
> > > > > > 
> > > > > > wont fix
> > > > > 
> > > > > 
> > > > > wont fix
> > > > 
> > > > 
> > > > wont fix
> > > 
> > > 
> > > farming commits
> > 
> > 
> > twitter for android
> 
> day after day

nn

**Comment by twnlink** [comment]
@9hp hey here's a good idea can you just
D E L E T E  T H I S  R E P O ?

**Comment by aspencuozzo** [comment]
> > > > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > > > 
> > > > > > > 
> > > > > > > wont fix
> > > > > > 
> > > > > > 
> > > > > > wont fix
> > > > > 
> > > > > 
> > > > > wont fix
> > > > 
> > > > 
> > > > farming commits
> > > 
> > > 
> > > twitter for android
> > 
> > 
> > day after day
> 
> nn

i have gotten 30 fucking emails for this one issue

**Comment by Aria-NL** [comment]
![you_know_what_time_it_is](https://user-images.githubusercontent.com/14789279/55450553-90dade00-559d-11e9-8064-d1d349793b61.gif)

**Comment by relative2** [comment]
> 
> 
> > > > > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > > > > 
> > > > > > > > 
> > > > > > > > wont fix
> > > > > > > 
> > > > > > > 
> > > > > > > wont fix
> > > > > > 
> > > > > > 
> > > > > > wont fix
> > > > > 
> > > > > 
> > > > > farming commits
> > > > 
> > > > 
> > > > twitter for android
> > > 
> > > 
> > > day after day
> > 
> > 
> > nn
> 
> i have gotten 30 fucking emails for this one issue

love you

**Comment by DashLt** [comment]
> > > > > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > > > > 
> > > > > > > > 
> > > > > > > > wont fix
> > > > > > > 
> > > > > > > 
> > > > > > > wont fix
> > > > > > 
> > > > > > 
> > > > > > wont fix
> > > > > 
> > > > > 
> > > > > farming commits
> > > > 
> > > > 
> > > > twitter for android
> > > 
> > > 
> > > day after day
> > 
> > 
> > nn
> 
> i have gotten 30 fucking emails for this one issue

as we all have

**Comment by relative2** [comment]
> 
> 
> > > > > > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > wont fix
> > > > > > > > 
> > > > > > > > 
> > > > > > > > wont fix
> > > > > > > 
> > > > > > > 
> > > > > > > wont fix
> > > > > > 
> > > > > > 
> > > > > > farming commits
> > > > > 
> > > > > 
> > > > > twitter for android
> > > > 
> > > > 
> > > > day after day
> > > 
> > > 
> > > nn
> > 
> > 
> > i have gotten 30 fucking emails for this one issue
> 
> as we all have

you're an nn

**Comment by Aria-NL** [comment]
![hellogais](https://user-images.githubusercontent.com/14789279/55450597-c253a980-559d-11e9-8565-8f88c0fa7c99.gif)

**Comment by DashLt** [comment]
> > > > > > > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > wont fix
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > wont fix
> > > > > > > > 
> > > > > > > > 
> > > > > > > > wont fix
> > > > > > > 
> > > > > > > 
> > > > > > > farming commits
> > > > > > 
> > > > > > 
> > > > > > twitter for android
> > > > > 
> > > > > 
> > > > > day after day
> > > > 
> > > > 
> > > > nn
> > > 
> > > 
> > > i have gotten 30 fucking emails for this one issue
> > 
> > 
> > as we all have
> 
> you're an nn

people who say 'nn' are the types to post quotes saying 'it doesn't matter who you are or where you came from but what you do' and call them deep

**Comment by 9hp** [comment]
http://www.themostamazingwebsiteontheinternet.com/ sneknet.com redesign

**Comment by aspencuozzo** [comment]
> > > > > > > > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > wont fix
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > wont fix
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > wont fix
> > > > > > > > 
> > > > > > > > 
> > > > > > > > farming commits
> > > > > > > 
> > > > > > > 
> > > > > > > twitter for android
> > > > > > 
> > > > > > 
> > > > > > day after day
> > > > > 
> > > > > 
> > > > > nn
> > > > 
> > > > 
> > > > i have gotten 30 fucking emails for this one issue
> > > 
> > > 
> > > as we all have
> > 
> > 
> > you're an nn
> 
> people who say 'nn' are the types to post quotes saying 'it doesn't matter who you are or where you came from but what you do' and call them deep

says the yuri degenerate

**Comment by relative2** [comment]
> 
> 
> > > > > > > > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > wont fix
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > wont fix
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > wont fix
> > > > > > > > 
> > > > > > > > 
> > > > > > > > farming commits
> > > > > > > 
> > > > > > > 
> > > > > > > twitter for android
> > > > > > 
> > > > > > 
> > > > > > day after day
> > > > > 
> > > > > 
> > > > > nn
> > > > 
> > > > 
> > > > i have gotten 30 fucking emails for this one issue
> > > 
> > > 
> > > as we all have
> > 
> > 
> > you're an nn
> 
> people who say 'nn' are the types to post quotes saying 'it doesn't matter who you are or where you came from but what you do' and call them deep

see you on hvh.aimwa.re:27035

**Comment by DashLt** [comment]
> > > > > > > > > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > wont fix
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > wont fix
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > wont fix
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > farming commits
> > > > > > > > 
> > > > > > > > 
> > > > > > > > twitter for android
> > > > > > > 
> > > > > > > 
> > > > > > > day after day
> > > > > > 
> > > > > > 
> > > > > > nn
> > > > > 
> > > > > 
> > > > > i have gotten 30 fucking emails for this one issue
> > > > 
> > > > 
> > > > as we all have
> > > 
> > > 
> > > you're an nn
> > 
> > 
> > people who say 'nn' are the types to post quotes saying 'it doesn't matter who you are or where you came from but what you do' and call them deep
> 
> says the yuri degenerate

how is that even relevant

**Comment by 9hp** [comment]
> http://www.themostamazingwebsiteontheinternet.com/ sneknet.com redesign

**Comment by tzAria** [comment]
how are you even relevant 

> > > > > > > > > > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > wont fix
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > wont fix
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > wont fix
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > farming commits
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > twitter for android
> > > > > > > > 
> > > > > > > > 
> > > > > > > > day after day
> > > > > > > 
> > > > > > > 
> > > > > > > nn
> > > > > > 
> > > > > > 
> > > > > > i have gotten 30 fucking emails for this one issue
> > > > > 
> > > > > 
> > > > > as we all have
> > > > 
> > > > 
> > > > you're an nn
> > > 
> > > 
> > > people who say 'nn' are the types to post quotes saying 'it doesn't matter who you are or where you came from but what you do' and call them deep
> > 
> > 
> > says the yuri degenerate
> 
> how is that even relevant

**Comment by aspencuozzo** [comment]
> > > > > > > > > > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > wont fix
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > wont fix
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > wont fix
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > farming commits
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > twitter for android
> > > > > > > > 
> > > > > > > > 
> > > > > > > > day after day
> > > > > > > 
> > > > > > > 
> > > > > > > nn
> > > > > > 
> > > > > > 
> > > > > > i have gotten 30 fucking emails for this one issue
> > > > > 
> > > > > 
> > > > > as we all have
> > > > 
> > > > 
> > > > you're an nn
> > > 
> > > 
> > > people who say 'nn' are the types to post quotes saying 'it doesn't matter who you are or where you came from but what you do' and call them deep
> > 
> > 
> > says the yuri degenerate
> 
> how is that even relevant

you legally do not have the right to criticize anyone

**Comment by DashLt** [comment]
> > > > > > > > > > > > > > > excuse me remove that fucking wontfix label you little shit
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > wont fix
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > wont fix
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > wont fix
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > farming commits
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > twitter for android
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > day after day
> > > > > > > > 
> > > > > > > > 
> > > > > > > > nn
> > > > > > > 
> > > > > > > 
> > > > > > > i have gotten 30 fucking emails for this one issue
> > > > > > 
> > > > > > 
> > > > > > as we all have
> > > > > 
> > > > > 
> > > > > you're an nn
> > > > 
> > > > 
> > > > people who say 'nn' are the types to post quotes saying 'it doesn't matter who you are or where you came from but what you do' and call them deep
> > > 
> > > 
> > > says the yuri degenerate
> > 
> > 
> > how is that even relevant
> 
> you legally do not have the right to criticize anyone

i don't unless they criticize me :^)
